name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   continue-on-error: true

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Lint
  #       run: cargo clippy
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
